"""autogenerated_initial_schema

Revision ID: f573c0147ed2
Revises: 0001
Create Date: 2026-05-01 15:04:07.073966
"""
from __future__ import annotations
from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'f573c0147ed2'
down_revision: str | None = '0001'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_grants', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('admin_grants', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('advisor_responses', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('advisor_responses', sa.Column('identity_instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('advisor_responses', sa.Column('interaction_frame_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('advisor_responses', sa.Column('blueprint_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('advisor_responses', sa.Column('direct_answer', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False))
    op.add_column('advisor_responses', sa.Column('what_user_state_suggests', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.add_column('advisor_responses', sa.Column('what_core_blueprint_corrects', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.add_column('advisor_responses', sa.Column('reality_check_summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.add_column('advisor_responses', sa.Column('stable_advice', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False))
    op.add_column('advisor_responses', sa.Column('best_next_action', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False))
    op.add_column('advisor_responses', sa.Column('risks', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.add_column('advisor_responses', sa.Column('uncertainty', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False))
    op.add_column('advisor_responses', sa.Column('confidence_score', sa.Float(), nullable=False))
    op.add_column('advisor_responses', sa.Column('residual_score', sa.Float(), nullable=False))
    op.add_column('advisor_responses', sa.Column('strain_score', sa.Float(), nullable=False))
    op.alter_column('advisor_responses', 'blueprint_checksum',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('advisor_responses', 'closure_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advisor_responses', 'leakage_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advisor_responses', 'compatibility_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('advisor_responses', 'advice_trace_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('advisor_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_advisor_responses_frame_id'), table_name='advisor_responses')
    op.create_index(op.f('ix_advisor_responses_user_id'), 'advisor_responses', ['user_id'], unique=False)
    op.drop_constraint(op.f('advisor_responses_frame_id_fkey'), 'advisor_responses', type_='foreignkey')
    op.create_foreign_key(None, 'advisor_responses', 'identity_mind_instances', ['identity_instance_id'], ['instance_id'])
    op.create_foreign_key(None, 'advisor_responses', 'core_mind_blueprints', ['blueprint_version_id'], ['blueprint_id'])
    op.create_foreign_key(None, 'advisor_responses', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'advisor_responses', 'interaction_frames', ['interaction_frame_id'], ['frame_id'])
    op.drop_column('advisor_responses', 'acknowledgment')
    op.drop_column('advisor_responses', 'frame_id')
    op.drop_column('advisor_responses', 'guidance')
    op.drop_column('advisor_responses', 'confidence')
    op.drop_column('advisor_responses', 'identity_reflection')
    op.drop_column('advisor_responses', 'clarifying_question')
    op.drop_column('advisor_responses', 'warning')
    op.drop_column('advisor_responses', 'safety_note')
    op.drop_column('advisor_responses', 'suggested_action')
    op.add_column('audit_logs', sa.Column('audit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('audit_logs', sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.add_column('audit_logs', sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_redacted', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'log_id')
    op.add_column('core_mind_blueprints', sa.Column('moral_kernel_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('fact_kernel_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('guidance_kernel_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('safety_kernel_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('training_dataset_refs', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('core_mind_blueprints', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('core_mind_blueprints', sa.Column('released_at', sa.DateTime(), nullable=True))
    op.add_column('core_mind_blueprints', sa.Column('changelog', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('core_mind_blueprints', 'checksum',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('core_mind_blueprints', 'signature',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('core_mind_blueprints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('core_mind_blueprints_version_key'), 'core_mind_blueprints', type_='unique')
    op.create_index(op.f('ix_core_mind_blueprints_status'), 'core_mind_blueprints', ['status'], unique=False)
    op.create_index(op.f('ix_core_mind_blueprints_version'), 'core_mind_blueprints', ['version'], unique=True)
    op.create_foreign_key(None, 'core_mind_blueprints', 'core_mind_blueprints', ['previous_version_id'], ['blueprint_id'])
    op.drop_column('core_mind_blueprints', 'reality_weight')
    op.drop_column('core_mind_blueprints', 'closure_target')
    op.drop_column('core_mind_blueprints', 'non_harm_weight')
    op.drop_column('core_mind_blueprints', 'moral_weight')
    op.drop_column('core_mind_blueprints', 'compatibility_threshold')
    op.drop_column('core_mind_blueprints', 'factual_weight')
    op.drop_column('core_mind_blueprints', 'updated_at')
    op.drop_column('core_mind_blueprints', 'leakage_tolerance')
    op.drop_column('core_mind_blueprints', 'description')
    op.add_column('device_sessions', sa.Column('device_fingerprint_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('device_sessions', sa.Column('last_seen_at', sa.DateTime(), nullable=False))
    op.add_column('device_sessions', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.alter_column('device_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('device_sessions', 'last_used_at')
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('identity_mind_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('identity_mind_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('identity_mind_instances_user_id_key'), 'identity_mind_instances', type_='unique')
    op.create_index(op.f('ix_identity_mind_instances_user_id'), 'identity_mind_instances', ['user_id'], unique=True)
    op.add_column('interaction_frames', sa.Column('identity_instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('interaction_frames', sa.Column('input_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('interaction_frames', sa.Column('situation_summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('interaction_frames', sa.Column('detected_claims', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('interaction_frames', sa.Column('emotional_state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('interaction_frames', sa.Column('residual_novelty_score', sa.Float(), nullable=False))
    op.add_column('interaction_frames', sa.Column('compatibility_score', sa.Float(), nullable=False))
    op.add_column('interaction_frames', sa.Column('strain_score', sa.Float(), nullable=False))
    op.add_column('interaction_frames', sa.Column('lag_ms', sa.Float(), nullable=False))
    op.alter_column('interaction_frames', 'sanitized_input',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15000),
               nullable=True)
    op.alter_column('interaction_frames', 'closure_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('interaction_frames', 'leakage_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('interaction_frames', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'interaction_frames', 'identity_mind_instances', ['identity_instance_id'], ['instance_id'])
    op.drop_column('interaction_frames', 'strain_level')
    op.drop_column('interaction_frames', 'stability_band')
    op.drop_column('interaction_frames', 'blueprint_version')
    op.drop_column('knowledge_patterns', 'embedding')
    op.add_column('knowledge_patterns', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.alter_column('knowledge_patterns', 'tags',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('knowledge_patterns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('knowledge_patterns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('refresh_tokens', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('used_at', sa.DateTime(), nullable=True))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['user_id'])
    op.add_column('screen_frames', sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.add_column('screen_frames', sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=True))
    op.add_column('screen_frames', sa.Column('detected_claims', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('screen_frames', sa.Column('sensitive_screen_detected', sa.Boolean(), nullable=False))
    op.alter_column('screen_frames', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('screen_frames', 'text_excerpt')
    op.drop_column('screen_frames', 'input_type')
    op.add_column('screen_guardian_verdicts', sa.Column('screen_frame_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('screen_guardian_verdicts', sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.add_column('screen_guardian_verdicts', sa.Column('suggested_user_action', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.alter_column('screen_guardian_verdicts', 'claim',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=False)
    op.alter_column('screen_guardian_verdicts', 'manipulation_signals',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('screen_guardian_verdicts', 'suggested_reply',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=True)
    op.alter_column('screen_guardian_verdicts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_screen_guardian_verdicts_frame_id'), table_name='screen_guardian_verdicts')
    op.drop_constraint(op.f('screen_guardian_verdicts_frame_id_fkey'), 'screen_guardian_verdicts', type_='foreignkey')
    op.create_foreign_key(None, 'screen_guardian_verdicts', 'screen_frames', ['screen_frame_id'], ['frame_id'])
    op.drop_column('screen_guardian_verdicts', 'frame_id')
    op.add_column('user_states', sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('user_states', sa.Column('intensity', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('pressure', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('confusion', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('urgency', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('fear', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('anger', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('sadness', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('attachment', sa.Float(), nullable=False))
    op.add_column('user_states', sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('user_states', sa.Column('context_summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('user_states', sa.Column('detected_risks', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('user_states', 'pressure_level')
    op.drop_column('user_states', 'fear_level')
    op.drop_column('user_states', 'urgency_level')
    op.drop_column('user_states', 'confusion_level')
    op.drop_column('user_states', 'attachment_level')
    op.drop_column('user_states', 'sadness_level')
    op.drop_column('user_states', 'anger_level')
    op.drop_column('user_states', 'emotional_intensity')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('user_states', sa.Column('emotional_intensity', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False))
    op.add_column('user_states', sa.Column('anger_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('user_states', sa.Column('sadness_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('user_states', sa.Column('attachment_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False))
    op.add_column('user_states', sa.Column('confusion_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('user_states', sa.Column('urgency_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('user_states', sa.Column('fear_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('user_states', sa.Column('pressure_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.alter_column('user_states', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('user_states', 'detected_risks')
    op.drop_column('user_states', 'context_summary')
    op.drop_column('user_states', 'goal')
    op.drop_column('user_states', 'attachment')
    op.drop_column('user_states', 'sadness')
    op.drop_column('user_states', 'anger')
    op.drop_column('user_states', 'fear')
    op.drop_column('user_states', 'urgency')
    op.drop_column('user_states', 'confusion')
    op.drop_column('user_states', 'pressure')
    op.drop_column('user_states', 'intensity')
    op.drop_column('user_states', 'emotion')
    op.add_column('screen_guardian_verdicts', sa.Column('frame_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'screen_guardian_verdicts', type_='foreignkey')
    op.create_foreign_key(op.f('screen_guardian_verdicts_frame_id_fkey'), 'screen_guardian_verdicts', 'screen_frames', ['frame_id'], ['frame_id'])
    op.create_index(op.f('ix_screen_guardian_verdicts_frame_id'), 'screen_guardian_verdicts', ['frame_id'], unique=False)
    op.alter_column('screen_guardian_verdicts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('screen_guardian_verdicts', 'suggested_reply',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screen_guardian_verdicts', 'manipulation_signals',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screen_guardian_verdicts', 'claim',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('screen_guardian_verdicts', 'suggested_user_action')
    op.drop_column('screen_guardian_verdicts', 'reason')
    op.drop_column('screen_guardian_verdicts', 'screen_frame_id')
    op.add_column('screen_frames', sa.Column('input_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('screen_frames', sa.Column('text_excerpt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('screen_frames', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('screen_frames', 'sensitive_screen_detected')
    op.drop_column('screen_frames', 'detected_claims')
    op.drop_column('screen_frames', 'extracted_text')
    op.drop_column('screen_frames', 'source_type')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('refresh_tokens', 'used_at')
    op.drop_column('refresh_tokens', 'user_id')
    op.alter_column('knowledge_patterns', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('knowledge_patterns', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('knowledge_patterns', 'tags',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.drop_column('knowledge_patterns', 'embedding')
    op.add_column('knowledge_patterns', sa.Column('embedding', sa.TEXT(), nullable=True))
    op.add_column('interaction_frames', sa.Column('blueprint_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interaction_frames', sa.Column('stability_band', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interaction_frames', sa.Column('strain_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interaction_frames', type_='foreignkey')
    op.alter_column('interaction_frames', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('interaction_frames', 'leakage_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('interaction_frames', 'closure_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('interaction_frames', 'sanitized_input',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15000),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('interaction_frames', 'lag_ms')
    op.drop_column('interaction_frames', 'strain_score')
    op.drop_column('interaction_frames', 'compatibility_score')
    op.drop_column('interaction_frames', 'residual_novelty_score')
    op.drop_column('interaction_frames', 'emotional_state')
    op.drop_column('interaction_frames', 'detected_claims')
    op.drop_column('interaction_frames', 'situation_summary')
    op.drop_column('interaction_frames', 'input_mode')
    op.drop_column('interaction_frames', 'identity_instance_id')
    op.drop_index(op.f('ix_identity_mind_instances_user_id'), table_name='identity_mind_instances')
    op.create_unique_constraint(op.f('identity_mind_instances_user_id_key'), 'identity_mind_instances', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('identity_mind_instances', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('identity_mind_instances', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('feedback', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('device_sessions', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('device_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('device_sessions', 'revoked_at')
    op.drop_column('device_sessions', 'last_seen_at')
    op.drop_column('device_sessions', 'device_fingerprint_hash')
    op.add_column('core_mind_blueprints', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('leakage_tolerance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('factual_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('compatibility_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('moral_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('non_harm_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('closure_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('core_mind_blueprints', sa.Column('reality_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'core_mind_blueprints', type_='foreignkey')
    op.drop_index(op.f('ix_core_mind_blueprints_version'), table_name='core_mind_blueprints')
    op.drop_index(op.f('ix_core_mind_blueprints_status'), table_name='core_mind_blueprints')
    op.create_unique_constraint(op.f('core_mind_blueprints_version_key'), 'core_mind_blueprints', ['version'], postgresql_nulls_not_distinct=False)
    op.alter_column('core_mind_blueprints', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('core_mind_blueprints', 'signature',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('core_mind_blueprints', 'checksum',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('core_mind_blueprints', 'changelog')
    op.drop_column('core_mind_blueprints', 'released_at')
    op.drop_column('core_mind_blueprints', 'approved_at')
    op.drop_column('core_mind_blueprints', 'approved_by')
    op.drop_column('core_mind_blueprints', 'training_dataset_refs')
    op.drop_column('core_mind_blueprints', 'safety_kernel_version')
    op.drop_column('core_mind_blueprints', 'guidance_kernel_version')
    op.drop_column('core_mind_blueprints', 'fact_kernel_version')
    op.drop_column('core_mind_blueprints', 'moral_kernel_version')
    op.add_column('audit_logs', sa.Column('log_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('audit_logs', 'metadata_redacted')
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'actor_type')
    op.drop_column('audit_logs', 'audit_id')
    op.add_column('advisor_responses', sa.Column('suggested_action', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('advisor_responses', sa.Column('safety_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('advisor_responses', sa.Column('warning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('advisor_responses', sa.Column('clarifying_question', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('advisor_responses', sa.Column('identity_reflection', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('advisor_responses', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('advisor_responses', sa.Column('guidance', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('advisor_responses', sa.Column('frame_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('advisor_responses', sa.Column('acknowledgment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'advisor_responses', type_='foreignkey')
    op.drop_constraint(None, 'advisor_responses', type_='foreignkey')
    op.drop_constraint(None, 'advisor_responses', type_='foreignkey')
    op.drop_constraint(None, 'advisor_responses', type_='foreignkey')
    op.create_foreign_key(op.f('advisor_responses_frame_id_fkey'), 'advisor_responses', 'interaction_frames', ['frame_id'], ['frame_id'])
    op.drop_index(op.f('ix_advisor_responses_user_id'), table_name='advisor_responses')
    op.create_index(op.f('ix_advisor_responses_frame_id'), 'advisor_responses', ['frame_id'], unique=False)
    op.alter_column('advisor_responses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('advisor_responses', 'advice_trace_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('advisor_responses', 'compatibility_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advisor_responses', 'leakage_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advisor_responses', 'closure_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('advisor_responses', 'blueprint_checksum',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('advisor_responses', 'strain_score')
    op.drop_column('advisor_responses', 'residual_score')
    op.drop_column('advisor_responses', 'confidence_score')
    op.drop_column('advisor_responses', 'uncertainty')
    op.drop_column('advisor_responses', 'risks')
    op.drop_column('advisor_responses', 'best_next_action')
    op.drop_column('advisor_responses', 'stable_advice')
    op.drop_column('advisor_responses', 'reality_check_summary')
    op.drop_column('advisor_responses', 'what_core_blueprint_corrects')
    op.drop_column('advisor_responses', 'what_user_state_suggests')
    op.drop_column('advisor_responses', 'direct_answer')
    op.drop_column('advisor_responses', 'blueprint_version_id')
    op.drop_column('advisor_responses', 'interaction_frame_id')
    op.drop_column('advisor_responses', 'identity_instance_id')
    op.drop_column('advisor_responses', 'user_id')
    op.alter_column('admin_grants', 'revoked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('admin_grants', 'granted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
