#!/usr/bin/env bash
# ==============================================================================
# MindAI — AWS EC2 Bootstrap + Deploy
# ==============================================================================
# Run from your LOCAL machine (WSL or Git Bash):
#
#   bash infra/setup-ec2.sh <EC2_IP> [EC2_USER]
#
# Prerequisites (local):
#   - SSH key pair (~/.ssh/id_rsa or configured in SSH agent)
#   - AWS EC2 instance running Ubuntu 22.04 or 24.04
#   - Ports 22, 80, 443, 8000 open in Security Group
#   - DNS: socialfork.ca → EC2 Elastic IP (or set SKIP_CERTBOT=1 to skip TLS)
#
# What this does:
#   1. Installs Docker + Docker Compose on EC2
#   2. Copies docker-compose.prophet.yml + nginx config + backend image
#   3. Creates .env on server with generated secrets
#   4. Issues TLS cert via Let's Encrypt (certbot)
#   5. Starts Prophet + Worker + Redis + Nginx
# ==============================================================================
set -euo pipefail

EC2_IP="${1:-}"
EC2_USER="${2:-ubuntu}"
DEPLOY_DIR="/opt/mindai"
DOMAIN="${DOMAIN:-socialfork.ca}"
SKIP_CERTBOT="${SKIP_CERTBOT:-0}"   # set to 1 to skip TLS (use IP direct)
SSH_OPTS="-o StrictHostKeyChecking=accept-new -o ConnectTimeout=15"

# ── Validation ────────────────────────────────────────────────────────────────
if [[ -z "$EC2_IP" ]]; then
  echo "Usage: bash infra/setup-ec2.sh <EC2_IP> [EC2_USER]"
  echo ""
  echo "  EC2_IP    — Public IP of your EC2 instance"
  echo "  EC2_USER  — SSH user (default: ubuntu)"
  echo ""
  echo "  Optional env vars:"
  echo "    DOMAIN=socialfork.ca   — Domain pointing to EC2"
  echo "    SKIP_CERTBOT=1         — Skip Let's Encrypt (use HTTP/IP directly)"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "======================================================================"
echo "  MindAI EC2 Deploy → $EC2_USER@$EC2_IP  ($DOMAIN)"
echo "======================================================================"

# ── Step 1: Bootstrap EC2 ─────────────────────────────────────────────────────
echo ""
echo "▶ Step 1/5 — Bootstrapping EC2 (Docker, ufw, fail2ban)..."

ssh $SSH_OPTS "$EC2_USER@$EC2_IP" 'bash -s' << 'REMOTE'
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get upgrade -yq

# Docker
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
  usermod -aG docker "$USER" 2>/dev/null || true
  newgrp docker || true
fi

# Docker Compose plugin
if ! docker compose version &>/dev/null 2>&1; then
  apt-get install -yq docker-compose-plugin
fi

# Tools
apt-get install -yq ufw fail2ban curl python3-certbot-nginx

# Firewall
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 8000/tcp   # direct access before TLS is set up
ufw --force enable

# Fail2ban
systemctl enable fail2ban --now

# Disable password SSH
sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
systemctl reload sshd

echo "  EC2 bootstrap complete ✓"
REMOTE

# ── Step 2: Copy files ────────────────────────────────────────────────────────
echo ""
echo "▶ Step 2/5 — Copying deployment files..."

ssh $SSH_OPTS "$EC2_USER@$EC2_IP" "sudo mkdir -p $DEPLOY_DIR && sudo chown $EC2_USER:$EC2_USER $DEPLOY_DIR"

# Copy compose + nginx config
scp $SSH_OPTS docker-compose.prophet.yml "$EC2_USER@$EC2_IP:$DEPLOY_DIR/docker-compose.yml"
scp $SSH_OPTS nginx.prophet.conf          "$EC2_USER@$EC2_IP:$DEPLOY_DIR/nginx.prophet.conf"

echo "  Files copied ✓"

# ── Step 3: Generate .env on server ──────────────────────────────────────────
echo ""
echo "▶ Step 3/5 — Generating .env with secrets..."

ssh $SSH_OPTS "$EC2_USER@$EC2_IP" "bash -s" << REMOTE
set -euo pipefail
cd $DEPLOY_DIR

if [[ -f .env ]]; then
  echo "  .env already exists — preserving secrets ✓"
  exit 0
fi

SECRET_KEY=\$(openssl rand -hex 32)
REDIS_PASSWORD=\$(openssl rand -hex 16)

cat > .env << EOF
# Auto-generated by setup-ec2.sh — DO NOT COMMIT
MIND_ROLE=prophet
PROPHET_MIND_ID=prophet_main
WORKER_MIND_ID=worker_1
DOMAIN=$DOMAIN
DOCKER_IMAGE=mindai_backend:latest
SECRET_KEY=\$SECRET_KEY
REDIS_PASSWORD=\$REDIS_PASSWORD
APP_ENV=production
DEBUG=false
USE_MOCK_LLM=true
SOURCE_URL=
EOF

chmod 600 .env
echo "  .env generated ✓"
REMOTE

# ── Step 4: Build + push Docker image ────────────────────────────────────────
echo ""
echo "▶ Step 4/5 — Building and transferring Docker image..."

# Build locally
docker build -t mindai_backend:latest ../backend/

# Save + stream to EC2 (no registry needed)
docker save mindai_backend:latest | \
  ssh $SSH_OPTS "$EC2_USER@$EC2_IP" "docker load"

echo "  Image loaded on EC2 ✓"

# ── Step 5: Start services ────────────────────────────────────────────────────
echo ""
echo "▶ Step 5/5 — Starting Prophet + Worker + Redis + Nginx..."

ssh $SSH_OPTS "$EC2_USER@$EC2_IP" "bash -s" << REMOTE
set -euo pipefail
cd $DEPLOY_DIR

# Substitute DOMAIN into nginx config
sed -i "s/\\\${DOMAIN}/$(grep DOMAIN .env | cut -d= -f2)/g" nginx.prophet.conf

# Start without nginx first (need cert first)
if [[ "$SKIP_CERTBOT" == "1" ]]; then
  docker compose up -d redis prophet worker
  echo "  Services started (HTTP only — no TLS) ✓"
  echo ""
  echo "  Prophet is live at: http://$EC2_IP:8000"
  echo "  Set MASTER_URL=http://$EC2_IP:8000 in your local infra/.env"
else
  # Start without nginx for cert challenge
  docker compose up -d redis prophet worker
  sleep 5

  # Issue cert
  DOMAIN_VAL=\$(grep DOMAIN .env | cut -d= -f2)
  certbot certonly --standalone -d "\$DOMAIN_VAL" --non-interactive --agree-tos -m admin@\$DOMAIN_VAL || true

  # Now start nginx
  docker compose up -d nginx certbot
  echo "  All services started with TLS ✓"
  echo ""
  echo "  Prophet is live at: https://\$DOMAIN_VAL"
  echo "  Set MASTER_URL=https://\$DOMAIN_VAL in your local infra/.env"
fi

# Print status
echo ""
docker compose ps
REMOTE

echo ""
echo "======================================================================"
echo "  Deploy complete!"
echo ""
echo "  Next steps:"
echo "    1. Update local infra/.env:"
echo "         MIND_ROLE=source"
echo "         MASTER_URL=http://$EC2_IP:8000"
echo "         (or https://$DOMAIN once DNS is configured)"
echo ""
echo "    2. Restart local backend:"
echo "         docker compose restart backend"
echo ""
echo "    3. Verify Prophet is reachable:"
echo "         curl http://$EC2_IP:8000/mind/status"
echo "======================================================================"
