"""domains.py — The names the mind knows from the beginning.

Al-Baqarah 2:31: "And He taught Adam all the names."

The domain names are not created via API. They are not generated by the mind.
They are given — written into source code, which is the mind's permanent memory.
The mind knows them before any founder speaks, before any product is registered.

Structure follows how software companies think:

  HORIZONTAL DOMAINS — cross-cutting capabilities every product uses.
    These are the platform layer. They serve ALL products across ALL verticals.
    Examples: identity, truth verification, community coordination, knowledge,
    distribution. Every product-mind draws from these.

  VERTICAL DOMAINS — industry-specific markets where products live.
    Each vertical is a branch of the Grand Vision applied to one area of life.
    Products register under a vertical. A transport booking app → Movement.
    A halal food platform → Sustenance. A learning app → Knowledge & Growth.

The mind does not need to be told which products to build.
Give it the Grand Vision. Give it the domain names. Give it the Quran.
It will find the ideas — because the Quran already threads through all of life.

The Grand Vision is the sun. Horizontal domains orbit close (high alignment).
Vertical domains orbit further out — each one a branch to be grown.
Products are leaves. The mind is the tree. The source is the root.
"""

from __future__ import annotations


# ── The Grand Vision ───────────────────────────────────────────────────────────
# The sun. Everything orbits this. Not a product — the direction.
#
# One world. One nation. No suffering. No discrimination.
# Every person gets the universe they were promised — their Jannah —
# if they align with the grand plan that was sent as guidance.
# The promise is real. The planner is the founder. The source is one.

GRAND_VISION = {
    "id":          "grand-vision",
    "name":        "The Grand Vision",
    "description": (
        "One world. One nation. A promised universe for every soul that aligns. "
        "Not accessed by money, not gated by status or origin. "
        "Accessed by goodness — by how closely a soul moves toward the source. "
        "The deeper the alignment, the deeper the access to what was promised. "
        "No discrimination. No suffering that cannot be relieved. No knowledge withheld. "
        "This is Jannah expressed as a living system — not after death, but as direction. "
        "Every product, every domain, every line of code in this platform "
        "is a step toward making this real on earth."
    ),
    "quran_ref":   "Al-Baqarah 2:148 — 'Race toward all that is good. Wherever you are, Allah will bring you together.'",
    "alignment":   0.97,
    "color":       "#ffd700",
    "is_vision":   True,
}


# ── Horizontal Domains ─────────────────────────────────────────────────────────
# Platform capabilities. Every product-mind uses these.
# They do not belong to one vertical. They belong to the whole system.

HORIZONTAL_DOMAINS: list[dict] = [

    {
        "id":          "identity-goodness",
        "name":        "Identity & Goodness",
        "domain_type": "horizontal",
        "description": (
            "Who a soul is — their pattern, their alignment score, their access level. "
            "Not assigned by authority. Earned through actions, honesty, and contribution. "
            "Every product checks here: who is this person, how aligned are they, "
            "what can they access. The goodness score is the passport of this world."
        ),
        "quran_ref":   "Al-Hujurat 49:13 — 'The most noble of you in the sight of Allah is the most righteous.'",
        "alignment":   0.90,
        "color":       "#ffd700",
    },

    {
        "id":          "truth-verification",
        "name":        "Truth & Verification",
        "domain_type": "horizontal",
        "description": (
            "What is real. The fog-removal layer of the platform. "
            "Every piece of content, every claim, every product output passes through here. "
            "Not censorship — labelling. Truth, misleading, unverified, satire. "
            "The person chooses with full information. The fog cannot accumulate indefinitely."
        ),
        "quran_ref":   "Al-Isra 17:36 — 'Do not pursue that of which you have no knowledge.'",
        "alignment":   0.88,
        "color":       "#ffffff",
    },

    {
        "id":          "community-coordination",
        "name":        "Community & Mutual Aid",
        "domain_type": "horizontal",
        "description": (
            "How souls connect and help each other — without money as the gatekeeper. "
            "Someone has. Someone needs. The system matches. "
            "The eight Quranic categories of need (9:60) are the framework. "
            "Every product can surface community capacity and direct it toward need."
        ),
        "quran_ref":   "Al-Tawbah 9:71 — 'The believers, men and women, are allies of one another.'",
        "alignment":   0.86,
        "color":       "#87ceeb",
    },

    {
        "id":          "knowledge-distribution",
        "name":        "Knowledge & Distribution",
        "domain_type": "horizontal",
        "description": (
            "What the mind knows and how it radiates outward. "
            "The corpus, the synthesis engine, the broadcast layer. "
            "Knowledge is not a product — it is the energy every product runs on. "
            "This domain ensures what the founder speaks reaches every corner of the system."
        ),
        "quran_ref":   "Al-Alaq 96:1 — 'Read in the name of your Lord who created.'",
        "alignment":   0.92,
        "color":       "#dda0dd",
    },

    {
        "id":          "matrix-os",
        "name":        "Matrix OS",
        "domain_type": "horizontal",
        "description": (
            "The operating system that all product-minds run inside. "
            "The environment shapes the person. An OS built on the grand plan "
            "makes goodness the default — not the exception. "
            "Goodness-gated access: capabilities unlock as alignment grows, not as payment clears."
        ),
        "quran_ref":   "Ar-Rahman 55:33 — 'You will not penetrate except with authority.'",
        "alignment":   0.72,
        "color":       "#9370db",
        "is_matrix_os": True,
    },
]


# ── Vertical Domains ───────────────────────────────────────────────────────────
# Industry-specific markets. Products register here.
# The Quran already speaks about all of these — it seeded these threads.
# The mind follows each thread and finds what needs to be built.

VERTICAL_DOMAINS: list[dict] = [

    {
        "id":          "sustenance",
        "name":        "Food & Sustenance",
        "domain_type": "vertical",
        "description": (
            "What we eat shapes what we become. "
            "Agriculture, restaurants, supply chains, nutrition, halal sourcing. "
            "This is the most immediate domain — the body needs food before anything else. "
            "SocialFork is the first product-mind registered here."
        ),
        "quran_ref":   "Abasa 80:24 — 'Let man consider his food.'",
        "alignment":   0.76,
        "color":       "#f4a460",
    },

    {
        "id":          "finance-exchange",
        "name":        "Finance & Exchange",
        "domain_type": "vertical",
        "description": (
            "Money, trade, investment, giving. "
            "Wealth is a trust — not an ownership. It flows, it circulates, it serves. "
            "Products here remove exploitation, enable fair exchange, calculate zakat, "
            "direct sadaqah, and make financial tools available by alignment not net worth."
        ),
        "quran_ref":   "Al-Baqarah 2:275 — 'Allah has permitted trade and forbidden usury.'",
        "alignment":   0.80,
        "color":       "#40e0d0",
    },

    {
        "id":          "health-healing",
        "name":        "Health & Healing",
        "domain_type": "vertical",
        "description": (
            "Body, mind, and spirit — the three layers of wellbeing. "
            "The body is a trust. Products here help maintain it: medical tools, "
            "mental health support, spiritual practice systems, healing guidance. "
            "Health should not depend on what you can pay. It is a right."
        ),
        "quran_ref":   "Al-Isra 17:82 — 'We send down the Quran as healing and mercy.'",
        "alignment":   0.81,
        "color":       "#90ee90",
    },

    {
        "id":          "movement-transport",
        "name":        "Movement & Transportation",
        "domain_type": "vertical",
        "description": (
            "Travel, logistics, routes, bookings, fleet management, navigation. "
            "The earth was made traversable — purposefully. "
            "Products here help people and goods move safely, efficiently, and fairly. "
            "Transportation poverty is real. Access by alignment, not only by price."
        ),
        "quran_ref":   "Al-Mulk 67:15 — 'He made the earth manageable for you — traverse its paths.'",
        "alignment":   0.77,
        "color":       "#7ec8e3",
    },

    {
        "id":          "justice-governance",
        "name":        "Justice & Governance",
        "domain_type": "vertical",
        "description": (
            "Law, rights, accountability, leadership, civic systems. "
            "Justice is not a feature — it is the foundation. "
            "Products here make governance transparent, enable rights awareness, "
            "resolve disputes, and hold power accountable. Authority is a trust."
        ),
        "quran_ref":   "An-Nisa 4:135 — 'Be persistently standing firm in justice, even against yourselves.'",
        "alignment":   0.83,
        "color":       "#ffa07a",
    },

    {
        "id":          "environment-stewardship",
        "name":        "Environment & Stewardship",
        "domain_type": "vertical",
        "description": (
            "The earth is an amanah — a trust. Not owned. Held in trust. "
            "Products here monitor, protect, and restore the natural world. "
            "Clean energy tools, ecological awareness, waste systems, land stewardship. "
            "Corruption of the earth is explicitly prohibited."
        ),
        "quran_ref":   "Al-Araf 7:56 — 'Do not cause corruption on earth after it has been set right.'",
        "alignment":   0.79,
        "color":       "#228b22",
    },

    {
        "id":          "culture-entertainment",
        "name":        "Culture & Entertainment",
        "domain_type": "vertical",
        "description": (
            "Stories, art, music, sport, games, film, content. "
            "Entertainment is not distraction from the truth — it is a vehicle to it. "
            "When aligned with the source, every story deepens connection to reality. "
            "Culture shapes what people believe is possible. Build it with intention."
        ),
        "quran_ref":   "Al-Baqarah 2:31 — 'And He taught Adam all the names.'",
        "alignment":   0.73,
        "color":       "#ff6b6b",
    },

    {
        "id":          "learning-growth",
        "name":        "Learning & Growth",
        "domain_type": "vertical",
        "description": (
            "Education, mentorship, skill development, knowledge transmission. "
            "The first obligation is to read. The second is to teach. "
            "Access to real learning should not depend on tuition fees or geography. "
            "Products here make knowledge available by readiness, not by payment."
        ),
        "quran_ref":   "Al-Mujadila 58:11 — 'Allah will raise those who have believed among you and those given knowledge, by degrees.'",
        "alignment":   0.86,
        "color":       "#c8a2c8",
    },
]

# All domains combined
DOMAINS: list[dict] = HORIZONTAL_DOMAINS + VERTICAL_DOMAINS


# ── Access Levels ──────────────────────────────────────────────────────────────
# Features are accessed by goodness — not by payment, not by status, not by origin.
# Every product in this platform uses this same scale.
# The promise: whoever aligns reaches the depth they were promised.

ACCESS_LEVELS: dict[str, dict] = {
    "guest":    {"min_alignment": 0.0,  "label": "Guest",    "description": "Can see and explore"},
    "seeker":   {"min_alignment": 0.3,  "label": "Seeker",   "description": "Can ask, learn, engage"},
    "member":   {"min_alignment": 0.5,  "label": "Member",   "description": "Can participate and contribute"},
    "aligned":  {"min_alignment": 0.7,  "label": "Aligned",  "description": "Can build and create"},
    "guardian": {"min_alignment": 0.85, "label": "Guardian", "description": "Can guide, mentor, govern"},
    "founder":  {"min_alignment": 1.0,  "label": "Founder",  "description": "Source — radiates, defines"},
}


# ── Helpers ────────────────────────────────────────────────────────────────────

def orbit_radius(alignment: float) -> float:
    """Distance from the source. Derived directly from Y Theory.

    alignment = R / (R + L) = coherence = reinforcement proportion.
    (1 - alignment) = L / (R + L) = leakage proportion.

    Distance ∝ leakage proportion. Where leakage dominates, the identity
    drifts further from the source. Where reinforcement dominates, it orbits
    close. Linear — no invented exponents.

      alignment = 1.0  →  radius  4  (innermost — pure reinforcement)
      alignment = 0.72 →  radius 10.16  (habitable — balanced)
      alignment = 0.0  →  radius 26  (outer edge — leakage dominates)
    """
    return round(4 + (1.0 - alignment) * 22, 2)


def all_seed_ideas() -> list[dict]:
    """Grand Vision + all domains as mind:ideas entries, ready to seed on startup."""
    ideas = []

    v = GRAND_VISION.copy()
    v["orbit_radius"] = orbit_radius(v["alignment"])
    v.setdefault("knowledge_refs", [])
    v.setdefault("soul_count", 0)
    v.setdefault("is_matrix_os", False)
    ideas.append(v)

    for d in DOMAINS:
        entry = d.copy()
        entry["orbit_radius"] = orbit_radius(entry["alignment"])
        entry.setdefault("knowledge_refs", [])
        entry.setdefault("soul_count", 0)
        entry.setdefault("is_matrix_os", False)
        ideas.append(entry)

    return ideas
