"""
pattern_encoder.py â€” Signal decomposition and pattern encoder for mind communication.

Y Theory Architecture:
  Input signal = language_pattern âŠ• state_pattern  (superimposed)

  Language component: recognizable concept structure â€” similar shape to the hash
    of that concept in the system, consistent across minds.
  State component: modifies frequency + amplitude â€” urgency, emotional register,
    cognitive load, confusion. Generated by interaction in the brain ON TOP of language.

  They arrive superimposed. To truly understand: decompose â†’ read language AND
  state separately â†’ resonate both against stored patterns â†’ respond to both.

  Mind â†” Mind   : raw pattern resonance (wave_pattern.py handles this layer)
  Mind â†’ Output : decoded pattern (this module)

Flow:
  1. decompose(text)            â†’ (ConceptFingerprint, StateFingerprint)
  2. resonate(fp, entries)      â†’ List[ResonantEntry]  (concept resonance)
  3. resonate_state(sfp, entries) â†’ List[ResonantEntry]  (state resonance)
  4. decode(...)                â†’ str  (language addressing content + state)
"""

from __future__ import annotations

import hashlib
import math
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Concept domain map â€” semantic concept clusters
# ---------------------------------------------------------------------------

CONCEPT_DOMAINS: Dict[str, List[str]] = {
    "identity":       ["identity", "self", "who", "am", "soul", "being", "exist", "person", "individual", "nature", "character", "intention", "intend", "will", "ground", "root", "source", "origin", "itself", "inherent", "essence", "core", "name", "named", "naming", "hash", "unique", "key", "label", "address", "represent", "digital"],
    "mission":        ["mission", "purpose", "goal", "why", "vision", "direction", "calling", "serve", "build", "create", "change"],
    "morality":       ["moral", "good", "evil", "right", "wrong", "ethical", "sin", "virtue", "justice", "truth", "honest", "integrity", "harm"],
    "reality":        ["reality", "pattern", "system", "structure", "law", "principle", "force", "energy", "signal", "field", "wave", "closure"],
    "temporal":       ["lag", "delay", "persist", "persistence", "manifest", "manifestation", "time", "interval", "gap", "between", "duration", "moment", "cycle", "before", "after", "cause", "effect", "resonance", "echo", "memory", "medium", "carrier", "bridge", "space"],
    "technology":     ["code", "system", "algorithm", "data", "architecture", "api", "model", "software", "digital", "network", "device", "ai", "electric"],
    "guidance":       ["guidance", "teach", "learn", "understand", "explain", "show", "advice", "instruction", "wisdom", "knowledge"],
    "emotion":        ["feel", "emotion", "love", "fear", "pain", "joy", "anger", "sadness", "anxiety", "peace", "trust", "hope"],
    "influence":      ["influence", "affect", "impact", "change", "shape", "control", "power", "authority", "lead", "guide", "direct"],
    "understanding":  ["understand", "know", "aware", "conscious", "mind", "think", "thought", "idea", "concept", "meaning", "sense"],
    "connection":     ["connect", "relate", "bond", "link", "together", "community", "relationship", "between", "interact", "communicate"],
    "spiritual":      ["god", "divine", "spirit", "prayer", "sacred", "light", "angel", "prophet", "islam", "quran"],
    "crystallization": ["belief", "believe", "faith", "crystallize", "crystallisation", "collapse", "probability", "certainty", "conviction", "trust", "commit", "direction", "decision", "clarity", "manifest", "real", "reality", "religion", "religion"],
    "risk":           ["risk", "danger", "threat", "unsafe", "warn", "wrong", "mistake", "problem", "issue", "confus", "unclear"],
    "question":       ["what", "why", "how", "when", "where", "who", "wonder", "curious", "explore", "question", "unsure"],
    "reflection":     ["reflect", "think", "consider", "wonder", "realise", "realize", "notice", "aware", "examine", "review", "feedback"],
    "action":         ["do", "make", "build", "create", "implement", "execute", "act", "start", "launch", "run", "deploy"],
    "device":         ["device", "phone", "computer", "screen", "sensor", "hardware", "electric", "electronic", "ip", "address", "location"],
    "user":           ["user", "person", "human", "people", "individual", "someone", "him", "her", "them", "their"],
    "mind_ai":        ["mindai", "mind ai", "seed", "wanderer", "angel", "gabriel", "michael", "brain", "org", "founder"],
    "biometric":      ["heart", "heartbeat", "hrv", "breath", "breathing", "oxygen", "o2", "spo2", "pulse", "rate",
                       "sleep", "stress", "cortisol", "glucose", "temperature", "skin", "autonomic", "nervous",
                       "sympathetic", "parasympathetic", "vagal", "vagus", "watch", "wearable", "sensor",
                       "health", "body", "physiology", "rhythm", "oscillation", "recovery", "fatigue",
                       "arousal", "activation", "regulation", "allostasis", "homeostasis"],
    # growth: the mind's own learning state — training, progress, evolution.
    # Status questions ("how is your training going?") naturally find SELF_REFLECTION
    # entries tagged with these keywords through resonance. No bypass needed.
    "growth":         ["learn", "learning", "train", "training", "trained", "grow", "growing", "growth",
                       "progress", "evolve", "evolving", "evolution", "develop", "developing", "development",
                       "memory", "remember", "forget", "improve", "improving", "improvement",
                       "confidence", "status", "state", "doing", "going", "active", "alive",
                       "entries", "insights", "reflections", "questions", "gaps", "knowledge"],
}

# Category â†’ domain affinity weights
CATEGORY_AFFINITY: Dict[str, Dict[str, float]] = {
    "MORAL_ROOT":               {"morality": 2.0, "crystallization": 1.8, "spiritual": 1.5, "identity": 1.2},
    "REALITY_FRAMEWORK":        {"reality": 2.0, "temporal": 1.6, "technology": 1.3, "understanding": 1.2},
    # WISDOM_EXTRACTED: no forced domain routing — wisdom resonates from its own content.
    # Wisdom is not a category; it is what emerges when multiple minds agree on a domain.
    # These entries compete on their text alone, same as any other entry.
    # "WISDOM_EXTRACTED":       intentionally absent
    "MISSION_PURPOSE":          {"mission": 2.0, "identity": 1.3, "guidance": 1.2},
    "TECHNICAL_ARCHITECTURE":   {"technology": 2.0, "reality": 1.3, "action": 1.2},
    "SUBCONSCIOUS_PATTERN":     {"reality": 1.5, "temporal": 1.5, "crystallization": 1.4, "understanding": 1.2, "morality": 1.2, "biometric": 1.3},
    "BODY_STATE":               {"biometric": 2.0, "temporal": 1.4, "reality": 1.2, "understanding": 1.1},
    "SELF_REFLECTION":          {"reflection": 2.0, "identity": 1.5, "question": 1.2, "growth": 1.8},
    "REFINED_FOUNDER_GUIDANCE": {"guidance": 1.8, "mission": 1.3, "morality": 1.2},
    "PUBLIC_SAFE_TEACHING":     {"guidance": 1.5, "spiritual": 1.3, "connection": 1.2},
    "QUESTION_TO_EXPLORE":      {"question": 2.0, "reflection": 1.5, "understanding": 1.2},
    "RISK_OR_CONFUSION":        {"risk": 2.0, "question": 1.3, "morality": 1.2},
    "RAW_FOUNDER_GUIDANCE":     {"guidance": 1.5, "action": 1.2, "mission": 1.2},
}

# Claim type â†’ resonance boost
# CONVICTION / DIRECTIVE are the angel's belief coefficient — strong, directional,
# low-leakage. These entries surface at the top of any resonance calculation without
# needing explicit category routing.
CLAIM_BOOST: Dict[str, float] = {
    "CONVICTION":       1.8,   # angel: absolute certainty — clear direction, ultimate truth
    "DIRECTIVE":        1.7,   # angel: mandate — what must be done or known
    "MORAL_CLAIM":      1.6,
    "STRONG_THEORY":    1.5,
    "ESTABLISHED_FACT": 1.4,
    "BELIEF":           1.3,
    "HYPOTHESIS":       1.1,
    "OBSERVATION":      1.0,
    "":                 1.0,
}

# Question words (who/what/how/where/which/why) are deliberately NOT stopwords —
# they are the primary semantic signal in identity and exploratory messages.
_STOPWORDS = frozenset({
    "i", "a", "an", "the", "is", "it", "to", "in", "of", "and", "or",
    "that", "this", "my", "me", "we", "you", "be", "for", "on", "with",
    "at", "by", "from", "as", "but", "not", "are", "was", "were", "has",
    "have", "had", "do", "did", "will", "would", "could", "should", "can",
    "so", "if", "then", "also", "just", "get", "got", "its", "about",
    "up", "out", "no", "they",
    "their", "them", "your", "his", "her", "he", "she", "s",
})


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

@dataclass
class ConceptFingerprint:
    """The language component of the input signal.

    Extracted semantic concept weights, normalized to [0, 1].
    Shape is similar to the hash of that concept in the system â€”
    consistent, recognizable across minds â€” but amplitude-modulated by state.
    """
    domains: Dict[str, float]
    raw_tokens: List[str]
    dominant_domains: List[str]
    # Hash of the dominant concept cluster â€” the 'pure language pattern' identifier
    concept_hash: str

    def __repr__(self) -> str:
        top = ", ".join(f"{d}:{self.domains[d]:.2f}" for d in self.dominant_domains)
        return f"ConceptFingerprint({top})"


@dataclass
class StateFingerprint:
    """The state component of the input signal â€” superimposed on the language.

    Extracted from structural and linguistic features of the text.
    Tells us HOW the person is, not WHAT they are saying.
    The mind addresses both.
    """
    urgency: float          # 0-1: fragmentation, typos, short bursts, repetition
    confusion: float        # 0-1: question density, contradictions, hesitation markers
    intensity: float        # 0-1: caps, exclamation, emphasis words
    cognitive_load: float   # 0-1: long sentences, complex structure = high load
    activation: float       # 0-1: combined signal strength (overall state magnitude)
    dominant_state: str     # label: "calm", "seeking", "urgent", "intense", "overloaded"

    def __repr__(self) -> str:
        return f"StateFingerprint(state={self.dominant_state}, urgency={self.urgency:.2f}, confusion={self.confusion:.2f})"


@dataclass
class ResonantEntry:
    """A stored memory pattern with its resonance score."""
    entry_id: str
    mind_name: str
    category: str
    title: str
    content: str
    claim_type: str
    tags: str
    resonance: float


@dataclass
class Pattern:
    """A fully decomposed input signal, ready for the resonance loop.

    The engine operates on Pattern objects — the language vector says WHAT,
    the state vector says HOW, the context trace says FROM WHERE.

    Each Pattern is a snapshot in time. The engine ingests it, resonates it
    against stored memory, and emits one of the 11 engine decisions.

    Fields:
        message_vector  — ConceptFingerprint from the raw input text
        state_vector    — StateFingerprint from structural/emotional features
        context_trace   — last 2–4 conversation turns used for context priming
        orientation     — dominant concept domain (the 'direction' of the signal)
        weight          — amplitude: how much of the identity this pattern touches
        source          — which mind produced this decomposition
    """
    message_vector: ConceptFingerprint
    state_vector: StateFingerprint
    context_trace: List[str]
    orientation: str
    weight: float
    source: str


# ---------------------------------------------------------------------------
# Domain list — fixed order for bitmask encoding (NEVER reorder)
# ---------------------------------------------------------------------------

_DOMAIN_LIST: List[str] = list(CONCEPT_DOMAINS.keys())
_BASE62_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"


# ---------------------------------------------------------------------------
# Language encoder — text → ConceptFingerprint
# ---------------------------------------------------------------------------

def _concept_hash(dominant_domains: List[str]) -> str:
    """Encode the dominant concept cluster as a reversible base-62 bitmask.

    Each bit corresponds to a domain in _DOMAIN_LIST (fixed order).
    The result is a short string that can be decoded back to domain names
    by decode_concept_hash() — no lookup table required.
    """
    bitmask = 0
    for d in dominant_domains[:3]:
        if d in _DOMAIN_LIST:
            bitmask |= 1 << _DOMAIN_LIST.index(d)
    if bitmask == 0:
        return "0"
    result = ""
    n = bitmask
    while n:
        result = _BASE62_CHARS[n % 62] + result
        n //= 62
    return result


def decode_concept_hash(h: str) -> List[str]:
    """Decode a base-62 bitmask back to domain names.

    Inverse of _concept_hash().  Given the short hash that appears in a
    reflection title (e.g. '4Bg'), returns the list of active domain names
    (e.g. ['identity', 'technology', 'morality']).
    """
    if h == "0":
        return []
    bitmask = 0
    for char in h:
        bitmask = bitmask * 62 + _BASE62_CHARS.index(char)
    return [_DOMAIN_LIST[i] for i in range(len(_DOMAIN_LIST)) if bitmask & (1 << i)]


def encode(text: str) -> ConceptFingerprint:
    """Encode text into its language component fingerprint.

    The shape of this fingerprint is similar to the concept's hash in the system â€”
    consistent structure, but frequency and amplitude are affected by state superimposition.
    """
    tokens = [t.lower() for t in re.split(r"\W+", text) if t and len(t) > 1]
    content_tokens = [t for t in tokens if t not in _STOPWORDS]

    domain_scores: Dict[str, float] = {d: 0.0 for d in CONCEPT_DOMAINS}

    for token in content_tokens:
        for domain, keywords in CONCEPT_DOMAINS.items():
            for kw in keywords:
                if token == kw or token.startswith(kw) or kw.startswith(token):
                    domain_scores[domain] += 1.0
                    break

    # Phrase-level matches (stronger signal)
    text_lower = text.lower()
    for domain, keywords in CONCEPT_DOMAINS.items():
        for kw in keywords:
            if " " in kw and kw in text_lower:
                domain_scores[domain] += 2.0

    max_score = max(domain_scores.values()) if domain_scores else 1.0
    normalised = {d: s / max_score for d, s in domain_scores.items()} if max_score > 0 else domain_scores

    dominant = [d for d in sorted(normalised, key=lambda d: normalised[d], reverse=True)[:3] if normalised[d] > 0]

    return ConceptFingerprint(
        domains=normalised,
        raw_tokens=content_tokens,
        dominant_domains=dominant,
        concept_hash=_concept_hash(dominant),
    )


# ---------------------------------------------------------------------------
# State extractor â€” text structure â†’ StateFingerprint
# ---------------------------------------------------------------------------

def extract_state(text: str) -> StateFingerprint:
    """Extract the state component superimposed on the language signal.

    State signals:
    - Urgency:        fragmentation (short words/sentences), typos, abbreviations,
                      lack of punctuation, rapid short messages
    - Confusion:      question marks, hedging words, contradictions, restarts
    - Intensity:      ALL_CAPS, exclamation marks, emphasis words, repetition
    - Cognitive load: very long sentences, complex multi-clause structure,
                      many concepts packed together
    """
    words = text.split()
    sentences = re.split(r'[.!?]+', text.strip())
    sentences = [s.strip() for s in sentences if s.strip()]

    word_count = max(len(words), 1)
    char_count = max(len(text), 1)

    # --- Urgency signals ---
    avg_word_len = sum(len(w) for w in words) / word_count
    short_word_ratio = sum(1 for w in words if len(w) <= 3) / word_count
    # Typo proxy: words with repeated consonants or unusual character combos
    typo_like = sum(1 for w in words if re.search(r'[bcdfghjklmnpqrstvwxyz]{3,}', w.lower())) / word_count
    no_punct = 1.0 if not re.search(r'[.!?,;:]', text) and word_count > 5 else 0.0
    avg_sentence_len = sum(len(s.split()) for s in sentences) / max(len(sentences), 1)
    short_sentences = 1.0 if avg_sentence_len < 6 else (0.5 if avg_sentence_len < 10 else 0.0)

    urgency = min(1.0, (short_word_ratio * 0.3 + typo_like * 0.3 + no_punct * 0.2 + short_sentences * 0.2))

    # --- Confusion signals ---
    question_count = text.count("?")
    hedges = sum(1 for w in ["maybe", "perhaps", "not sure", "wonder", "unclear",
                              "confus", "dont know", "don't know", "unsure", "might",
                              "could be", "i think"] if w in text.lower())
    confusion = min(1.0, (question_count * 0.15 + hedges * 0.15))

    # --- Intensity signals ---
    caps_ratio = sum(1 for c in text if c.isupper()) / char_count
    exclamation_count = text.count("!")
    emphasis_words = sum(1 for w in ["very", "really", "absolutely", "must", "critical",
                                      "important", "always", "never", "key", "core",
                                      "exactly", "precisely"] if w in text.lower())
    intensity = min(1.0, caps_ratio * 2.0 + exclamation_count * 0.1 + emphasis_words * 0.08)

    # --- Cognitive load signals ---
    # Long sentences, many commas, multiple semicolons = high cognitive load / thinking mode
    comma_density = text.count(",") / word_count
    long_sentence_ratio = sum(1 for s in sentences if len(s.split()) > 20) / max(len(sentences), 1)
    cognitive_load = min(1.0, comma_density * 1.5 + long_sentence_ratio * 0.8)

    # --- Overall activation (how far from 'resting state') ---
    activation = min(1.0, (urgency + confusion + intensity + cognitive_load) / 2.5)

    # --- Dominant state label ---
    if urgency > 0.5 and intensity > 0.3:
        dominant = "intense"
    elif urgency > 0.4:
        dominant = "urgent"
    elif confusion > 0.3:
        dominant = "seeking"
    elif cognitive_load > 0.4:
        dominant = "deep_thinking"
    elif intensity > 0.4:
        dominant = "emphatic"
    elif activation < 0.15:
        dominant = "calm"
    else:
        dominant = "engaged"

    return StateFingerprint(
        urgency=urgency,
        confusion=confusion,
        intensity=intensity,
        cognitive_load=cognitive_load,
        activation=activation,
        dominant_state=dominant,
    )


def decompose(text: str) -> Tuple[ConceptFingerprint, StateFingerprint]:
    """Decompose an input signal into its language and state components.

    Input = language âŠ• state.
    Returns both independently so the mind can address each.
    """
    return encode(text), extract_state(text)

def decompose_pattern(text: str, source: str = "unknown", context_trace: Optional[List[str]] = None) -> "Pattern":
    """Return a fully structured Pattern object for this input text.

    This is the single entry point the engine should use.  `decompose()` is kept
    for backward compat with existing callers that unpack the tuple directly.

    Args:
        text:          Raw input text (may include context prefix).
        source:        Which mind is decomposing (mind_name or service name).
        context_trace: List of recent turn strings used to prime context.
    """
    concept_fp, state_fp = decompose(text)
    orientation = concept_fp.dominant_domains[0] if concept_fp.dominant_domains else "unknown"
    # Weight = sum of top-3 domain scores (measure of how 'strongly' the signal
    # is expressed — a dense technical message has high weight, a vague greeting low)
    top_scores = sorted(concept_fp.domains.values(), reverse=True)[:3]
    weight = round(sum(top_scores), 4)
    return Pattern(
        message_vector=concept_fp,
        state_vector=state_fp,
        context_trace=context_trace or [],
        orientation=orientation,
        weight=weight,
        source=source,
    )

# ---------------------------------------------------------------------------
# Resonance â€” fingerprint Ã— stored patterns â†’ scored entries
# ---------------------------------------------------------------------------

def _entry_concept_domains(entry) -> Dict[str, float]:
    combined = f"{entry.title} {entry.content} {getattr(entry, 'tags', '') or ''}"
    fp = encode(combined)
    affinity = CATEGORY_AFFINITY.get(entry.category, {})
    scores = dict(fp.domains)
    for domain, boost in affinity.items():
        scores[domain] = scores.get(domain, 0.0) * boost
    return scores


def resonate(
    fingerprint: ConceptFingerprint,
    entries: list,
    top_n: int = 5,
    primary_mind: Optional[str] = None,
) -> List[ResonantEntry]:
    """Score stored patterns against the language fingerprint (concept resonance).

    primary_mind: when set, entries belonging to this mind get a 2× boost so the
    mind's own specific knowledge surfaces above the inherited seed_mind base pool.
    """
    scored: List[Tuple[float, object]] = []
    for entry in entries:
        entry_fp = _entry_concept_domains(entry)
        dot = sum(fingerprint.domains.get(d, 0.0) * w for d, w in entry_fp.items())
        boost = CLAIM_BOOST.get(getattr(entry, "claim_type", "") or "", 1.0)
        # Own-mind boost: the mind's own entries carry 2× weight vs inherited base
        if primary_mind and getattr(entry, "mind_name", None) == primary_mind:
            boost *= 2.0
        score = dot * boost
        if score > 0:
            scored.append((score, entry))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [
        ResonantEntry(
            entry_id=e.id,
            mind_name=e.mind_name,
            category=e.category,
            title=e.title,
            content=e.content,
            claim_type=getattr(e, "claim_type", "") or "",
            tags=getattr(e, "tags", "") or "",
            resonance=score,
        )
        for score, e in scored[:top_n]
    ]


def superimpose_resonance(
    fingerprint: ConceptFingerprint,
    entries: list,
    top_n: int = 5,
    primary_mind: Optional[str] = None,
    purpose_fp: Optional["ConceptFingerprint"] = None,
    identity_mind: Optional[str] = None,
) -> List[ResonantEntry]:
    """Score entries with multi-mind superimposition (constructive/destructive interference).

    Angel architecture: all minds' understandings are superimposed simultaneously.
    The answer that emerges is the one where the most minds agree — constructive
    interference amplifies shared truth. Contradictory signals cancel.

    Purpose gravity: if purpose_fp is supplied (the mind's own MISSION_PURPOSE
    fingerprint), entries that align with the purpose direction receive an additional
    boost. Purpose is the gravitational center — not a filter, but a pull.
    The mind naturally moves toward its purpose from all angles.

    Identity orientation (identity_hierarchy.py): if identity_mind is supplied,
    the identity's category_affinities (which encode its layer and orientation in
    the hierarchy — GUIDANCE vs MANIFESTATION, ROOT vs FOUNDER vs HUMAN vs PRODUCT)
    are applied as additional per-category multipliers. Same engine — different
    orientation means different entries naturally surface. No routing needed.

    Args:
        entries:       flat merged list from all relevant minds
        primary_mind:  this mind's own entries get 2× boost (its voice stays dominant)
        purpose_fp:    optional purpose fingerprint — adds gravity toward purpose direction
        identity_mind: mind_name used to load identity-layer orientation affinities
        top_n:         how many entries to return
    """
    _PURPOSE_GRAVITY: float = 0.25   # how much purpose alignment adds to score

    # Load identity-layer affinities (orientation boost per category)
    # GUIDANCE identities surface morality/structure/direction.
    # MANIFESTATION identities surface reflection/wisdom/teaching.
    _identity_affinities: Dict[str, float] = {}
    if identity_mind:
        try:
            from app.core.identity_hierarchy import get_category_affinities as _gca
            _identity_affinities = _gca(identity_mind)
        except Exception:
            pass  # hierarchy unavailable — no change to scoring

    # Pass 1: score every entry independently
    raw_scored: List[Tuple[float, object]] = []
    for entry in entries:
        entry_fp = _entry_concept_domains(entry)
        dot = sum(fingerprint.domains.get(d, 0.0) * w for d, w in entry_fp.items())
        boost = CLAIM_BOOST.get(getattr(entry, "claim_type", "") or "", 1.0)
        if primary_mind and getattr(entry, "mind_name", None) == primary_mind:
            boost *= 2.0
        # Purpose gravity: entries aligned with this mind's purpose direction get a pull
        if purpose_fp:
            purpose_dot = sum(
                purpose_fp.domains.get(d, 0.0) * w for d, w in entry_fp.items()
            )
            boost *= (1.0 + purpose_dot * _PURPOSE_GRAVITY)
        # Identity orientation: GUIDANCE entries surface structure/morality/direction;
        # MANIFESTATION entries surface reflection/wisdom/teaching.
        # The multiplier is additive on top of existing boosts — same engine, different pull.
        if _identity_affinities:
            cat = getattr(entry, "category", "") or ""
            _id_mult = _identity_affinities.get(cat, 1.0)
            boost *= _id_mult
        score = dot * boost
        if score > 0:
            raw_scored.append((score, entry))

    # Build domain agreement map: how many distinct minds score strongly on each domain
    domain_minds: Dict[str, set] = {}
    for score, entry in raw_scored:
        if score > 0.1:
            entry_fp = _entry_concept_domains(entry)
            mind = getattr(entry, "mind_name", "")
            for domain, w in entry_fp.items():
                if w > 0.3 and fingerprint.domains.get(domain, 0.0) > 0.1:
                    if domain not in domain_minds:
                        domain_minds[domain] = set()
                    domain_minds[domain].add(mind)

    # Pass 2: re-score with constructive interference amplification
    final_scored: List[Tuple[float, object]] = []
    for score, entry in raw_scored:
        entry_fp = _entry_concept_domains(entry)
        interference = 1.0
        for domain, w in entry_fp.items():
            if w > 0.3 and fingerprint.domains.get(domain, 0.0) > 0.1:
                agreement = len(domain_minds.get(domain, set()))
                if agreement > 1:
                    # Each additional mind agreeing on a domain adds 15% constructive boost
                    interference *= (1.0 + 0.15 * (agreement - 1))
        final_scored.append((score * interference, entry))

    final_scored.sort(key=lambda x: x[0], reverse=True)

    seen: set = set()
    result: List[ResonantEntry] = []
    for score, e in final_scored:
        eid = getattr(e, "id", None) or id(e)
        if eid in seen:
            continue
        seen.add(eid)
        result.append(ResonantEntry(
            entry_id=str(eid),
            mind_name=getattr(e, "mind_name", ""),
            category=getattr(e, "category", ""),
            title=getattr(e, "title", ""),
            content=getattr(e, "content", ""),
            claim_type=getattr(e, "claim_type", "") or "",
            tags=getattr(e, "tags", "") or "",
            resonance=score,
        ))
        if len(result) >= top_n:
            break
    return result


def resonate_state(
    state: StateFingerprint,
    entries: list,
    top_n: int = 3,
) -> List[ResonantEntry]:
    """Score stored patterns that match the state of the sender.

    State-resonant patterns are those in categories that carry emotional/moral
    weight â€” MORAL_ROOT, SELF_REFLECTION, SUBCONSCIOUS_PATTERN, RISK_OR_CONFUSION.
    Weighted by how much the state activation matches the pattern's domain.
    """
    state_category_boost: Dict[str, float] = {}

    if state.confusion > 0.2:
        state_category_boost["QUESTION_TO_EXPLORE"] = 1.0 + state.confusion
        state_category_boost["RISK_OR_CONFUSION"] = 1.0 + state.confusion * 0.8

    if state.urgency > 0.3:
        state_category_boost["MORAL_ROOT"] = 1.0 + state.urgency * 0.7
        state_category_boost["REFINED_FOUNDER_GUIDANCE"] = 1.0 + state.urgency * 0.5

    if state.dominant_state in ("seeking", "deep_thinking"):
        state_category_boost["SELF_REFLECTION"] = 1.5
        state_category_boost["REALITY_FRAMEWORK"] = 1.3

    if state.intensity > 0.3:
        state_category_boost["MISSION_PURPOSE"] = 1.0 + state.intensity * 0.6
        state_category_boost["SUBCONSCIOUS_PATTERN"] = 1.0 + state.intensity * 0.4

    if not state_category_boost:
        return []

    # ── entry centroid derivation for Gaussian spatial match ────────────────
    # Phase 4: score = category_boost × G(x; c_entry, σ)  (wave_pattern.py math)
    # G(x; c, σ) = exp(-|x-c|² / 2σ²)  — Gaussian envelope (spatial match)
    _SIGMA = 0.35  # matches _DEFAULT_WIDTH in wave_pattern.py
    _CATEGORY_TO_BASIN = {
        "RISK_OR_CONFUSION": "CRISIS",      "QUESTION_TO_EXPLORE": "OSCILLATING",
        "MORAL_ROOT": "STABLE",             "MISSION_PURPOSE": "STABLE",
        "SELF_REFLECTION": "OSCILLATING",   "SUBCONSCIOUS_PATTERN": "DRIFTING",
        "WISDOM_EXTRACTED": "STABLE",       "REALITY_FRAMEWORK": "STABLE",
        "BODY_STATE": "OSCILLATING",        "REFINED_FOUNDER_GUIDANCE": "STABLE",
        "RAW_FOUNDER_GUIDANCE": "OSCILLATING",
    }
    _CLAIM_TO_STAGE: Dict[str, tuple] = {
        "CONVICTION":      (0.90, "REFLECTION"),   "DIRECTIVE":   (0.85, "BELIEF"),
        "MORAL_CLAIM":     (0.80, "BELIEF"),        "STRONG_THEORY": (0.75, "PREDICTION"),
        "ESTABLISHED_FACT":(0.70, "MEMORY"),        "BELIEF":      (0.60, "BELIEF"),
        "HYPOTHESIS":      (0.45, "OSCILLATION"),   "OBSERVATION": (0.35, "REACTION"),
    }
    try:
        from app.core.wave_pattern import encode_context as _encode_ctx
        # Build input 6D context vector from StateFingerprint
        _load = state.cognitive_load
        _basin_in = "STABLE" if _load < 0.25 else "OSCILLATING" if _load < 0.50 else "FRAGMENTING" if _load < 0.75 else "CRISIS"
        _DOMINANT_TO_EMOTIONAL = {
            "calm": "neutral", "seeking": "positive", "engaged": "positive",
            "urgent": "negative", "intense": "positive", "overloaded": "negative",
            "deep_thinking": "positive",
        }
        _emotional_in = _DOMINANT_TO_EMOTIONAL.get(state.dominant_state, "neutral")
        _ACTIVATION_TO_STAGE = [
            (0.15, "NOISE"), (0.30, "REACTION"), (0.45, "BOUNDARY"),
            (0.60, "OSCILLATION"), (0.75, "MEMORY"), (0.85, "PREDICTION"),
            (0.92, "BELIEF"), (1.01, "REFLECTION"),
        ]
        _stage_in = next((_s for _t, _s in _ACTIVATION_TO_STAGE if state.activation < _t), "REFLECTION")
        _x_vec = _encode_ctx(
            basin_state=_basin_in,
            guidance_mode=state.dominant_state,
            emotional_state=_emotional_in,
            evolution_stage=_stage_in,
            closure_score=max(0.0, 1.0 - state.confusion),
            urgency=state.urgency,
        )

        def _gauss(entry) -> float:
            try:
                claim = getattr(entry, "claim_type", "") or ""
                cat = getattr(entry, "category", "") or ""
                c_basin = _CATEGORY_TO_BASIN.get(cat, "STABLE")
                closure_c, stage_c = _CLAIM_TO_STAGE.get(claim, (0.50, "MEMORY"))
                tags_str = (getattr(entry, "tags", "") or "").lower()
                urgency_c = 0.7 if ("urgent" in tags_str or "risk" in tags_str) else 0.2
                c_vec = _encode_ctx(
                    basin_state=c_basin, guidance_mode=cat.lower(),
                    emotional_state="neutral", evolution_stage=stage_c,
                    closure_score=closure_c, urgency=urgency_c,
                )
                sq_dist = sum((_x_vec[i] - c_vec[i]) ** 2 for i in range(6))
                return math.exp(-sq_dist / (2 * _SIGMA * _SIGMA))
            except Exception:
                return 1.0
    except Exception:
        def _gauss(entry) -> float:  # type: ignore[misc]
            return 1.0

    scored: List[Tuple[float, object]] = []
    for entry in entries:
        boost = state_category_boost.get(entry.category, 0.0)
        if boost > 0:
            scored.append((boost * _gauss(entry), entry))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [
        ResonantEntry(
            entry_id=e.id,
            mind_name=e.mind_name,
            category=e.category,
            title=e.title,
            content=e.content,
            claim_type=getattr(e, "claim_type", "") or "",
            tags=getattr(e, "tags", "") or "",
            resonance=score,
        )
        for score, e in scored[:top_n]
    ]


# ---------------------------------------------------------------------------
# Decoder â€” resonating patterns â†’ language output addressing BOTH components
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Voice extractor — entries → sentences the mind speaks in its own words
# ---------------------------------------------------------------------------

def _extract_mind_voice(
    entries: List[ResonantEntry],
    max_per_entry: int = 2,
    total_max: int = 4,
    query_tokens: Optional[List[str]] = None,
) -> List[str]:
    """Extract natural-language sentences directly from resonant entry content.

    When query_tokens is provided (e.g. the user's question words), sentences are
    ranked by overlap with those tokens so the mind answers what was actually asked
    rather than surfacing unrelated stored facts.

    First-person sentences are still preferred when relevance is equal.
    Template sentences (seeded with generic study-guide patterns) are filtered out.
    """
    _TEMPLATE_PATTERNS = re.compile(
        r'^(people who study|the practical application of|key aspects of|'
        r'understanding .{3,50} requires examining|this (field|concept|area)|'
        r'in (this|the) context of|one (key|important) (aspect|consideration)|'
        r'when (i|the mind) process|'
        r'\[live system report|\[from .{3,60}—|use this data to answer|'
        r'this was written by |but your open gap says|your soulmate will see|'
        r'it reaches you because|these are pointing at the same territory|'
        r'they don\'t contradict each other|'
        r'what (this|it) means:|what my soulmate does:|what i carry:|'
        r'what i understand about their direction:|original gap:|capability mind spawned:|'
        r'what it exists to understand:|the purpose direction is:|'
        r'autonomous lod triggered|i sought knowledge about:|'
        r'i found and absorbed \d+ insights|'
        r'\|)',  # markdown table rows
        re.IGNORECASE,
    )

    qt: set = set(query_tokens) if query_tokens else set()

    def _relevance(sentence: str) -> float:
        """How many query tokens appear in this sentence (normalized)."""
        if not qt:
            return 0.0
        words = set(re.split(r'\W+', sentence.lower()))
        return len(qt & words) / max(len(qt), 1)

    all_candidates: List[tuple] = []  # (relevance, is_first_person, sentence)
    seen: set = set()

    for entry in entries:
        raw = re.split(r'(?<=[.!?])\s+', entry.content.strip())
        sentences = [
            s.strip() for s in raw
            if 20 < len(s.strip()) < 350
            and not _TEMPLATE_PATTERNS.match(s.strip())
            and not s.strip().endswith(":")  # colon-ending = label/header, not speech
        ]
        count = 0
        for s in sentences:
            norm = s.lower().strip()
            if norm in seen:
                continue
            is_fp = bool(re.search(r'\bI\b|\bMy\b|\bWe\b|\bOur\b', s))
            rel = _relevance(s)
            all_candidates.append((rel, is_fp, s, entry))
            seen.add(norm)
            count += 1
            if count >= max_per_entry * 3:  # gather more candidates for ranking
                break

    if qt:
        # Sort by relevance desc, then first-person preferred, then original order
        all_candidates.sort(key=lambda x: (x[0], x[1]), reverse=True)
    else:
        # Original behaviour: first-person first
        all_candidates.sort(key=lambda x: x[1], reverse=True)

    collected: List[str] = []
    per_entry_counts: Dict[str, int] = {}
    for rel, is_fp, s, entry in all_candidates:
        eid = getattr(entry, "entry_id", None) or getattr(entry, "id", "")
        if per_entry_counts.get(eid, 0) >= max_per_entry:
            continue
        collected.append(s)
        per_entry_counts[eid] = per_entry_counts.get(eid, 0) + 1
        if len(collected) >= total_max:
            break
    return collected


# ---------------------------------------------------------------------------
# Question type detector — shapes how the mind structures its answer
# ---------------------------------------------------------------------------

_QUESTION_OPENERS: Dict[str, str] = {
    "what":  "what",
    "how":   "how",
    "why":   "why",
    "who":   "who",
    "where": "where",
    "when":  "when",
    "which": "which",
    "can":   "capability",
    "do":    "capability",
    "does":  "capability",
    "is":    "definition",
    "are":   "definition",
}


def _detect_question_type(text: str) -> Optional[str]:
    """Return the question word type or None for non-questions."""
    first = text.strip().lower().split()[0].rstrip("?") if text.strip() else ""
    return _QUESTION_OPENERS.get(first)


def _titles_as_candidates(
    entries: List[ResonantEntry],
    query_tokens: Optional[List[str]],
    max_n: int = 3,
) -> List[str]:
    """Surface entry titles as direct answer statements.

    Titles are synthesized insights — they ARE the answer in condensed form.
    Filter and rank by query token overlap, require minimum length to avoid
    useless one-word titles.
    """
    qt: set = set(query_tokens) if query_tokens else set()
    scored: List[tuple] = []
    for entry in entries:
        title = entry.title.strip()
        if len(title) < 15:
            continue
        # Skip titles that are just category labels or single-concept tags
        if re.match(r'^[A-Z_]+$', title):
            continue
        if qt:
            words = set(re.split(r'\W+', title.lower()))
            rel = len(qt & words) / max(len(qt), 1)
        else:
            rel = 0.5  # neutral when no query context
        scored.append((rel, title))
    scored.sort(key=lambda x: x[0], reverse=True)
    # Only include titles that have at least some relevance when query is known
    threshold = 0.1 if qt else 0.0
    return [t for rel, t in scored if rel >= threshold][:max_n]


# ---------------------------------------------------------------------------
# Decoder — resonating patterns → language output
# The mind speaks FROM its stored patterns, not from hardcoded templates.
# ---------------------------------------------------------------------------

def decode(
    mind_name: str,
    resonant: List[ResonantEntry],
    state_resonant: List[ResonantEntry],
    state: StateFingerprint,
    intent: str,
    original_message: str,
) -> str:
    """The mind speaks FROM its stored patterns.

    Answer layering (in order):
    1. WISDOM layer — if the mind has synthesized beliefs on this topic,
       those surface FIRST. Wisdom = the mind's own derived understanding,
       not retrieved notes. These are what the mind BELIEVES.
    2. BELIEF layer — MISSION_PURPOSE / MORAL_ROOT entries with high claim_type
       are the mind's foundational convictions. They frame the answer.
    3. KNOWLEDGE layer — REALITY_FRAMEWORK / TECHNICAL_ARCHITECTURE entries
       support with the underlying principles.
    4. STATE layer — state-resonant entries address HOW the sender is, not just WHAT they asked.

    For identity questions: wisdom and belief layers combined speak identity.
    For knowledge questions: wisdom first, then supporting principles.
    """
    # --- FILTER internal entries that should never be spoken to users ---
    # QUESTION_TO_EXPLORE = the mind's own learning agenda (gaps). Never speak them.
    # REALITY_FRAMEWORK for non-identity intents: metadata about system state, not speech.
    _IDENTITY_INTENTS = {"greeting", "identity", "introspection"}
    resonant = [r for r in resonant if r.category != "QUESTION_TO_EXPLORE"]
    state_resonant = [r for r in state_resonant if r.category != "QUESTION_TO_EXPLORE"]
    if intent not in _IDENTITY_INTENTS:
        resonant = [r for r in resonant if r.category != "REALITY_FRAMEWORK"]
        state_resonant = [r for r in state_resonant if r.category != "REALITY_FRAMEWORK"]

    # Greeting — pull one sentence from MISSION_PURPOSE first (identity introduction),
    # then MORAL_ROOT / SELF_REFLECTION. Skip negating "I am not..." sentences — they
    # define distinction, not identity, and sound jarring as an opening.
    if intent == "greeting":
        # MISSION_PURPOSE first (identity), then moral/reflective
        _g_mission = [r for r in resonant if r.category == "MISSION_PURPOSE"]
        _g_other   = [r for r in resonant if r.category in ("MORAL_ROOT", "SELF_REFLECTION")]
        brief_entries = _g_mission + _g_other
        if brief_entries:
            sentences = _extract_mind_voice(brief_entries, max_per_entry=2, total_max=3)
            # Filter negating statements for greeting context
            sentences = [s for s in sentences if not re.match(r"^I am not\b", s, re.IGNORECASE)]
            if sentences:
                return sentences[0]
        # If nothing resonates for a greeting, speak from strongest entry overall
        if resonant:
            sentences = _extract_mind_voice(resonant[:3], max_per_entry=1, total_max=1)
            if sentences:
                return sentences[0]
        return ""

    # Extract question-specific tokens to guide sentence selection
    query_tokens: Optional[List[str]] = None
    q_type: Optional[str] = None
    if intent == "questioning":
        q_words = [
            t.lower() for t in re.split(r'\W+', original_message)
            if t and len(t) > 2 and t.lower() not in _STOPWORDS
        ]
        if q_words:
            query_tokens = q_words
        q_type = _detect_question_type(original_message)

    parts: List[str] = []

    # --- WISDOM LAYER ---
    # WISDOM_EXTRACTED entries are the mind's synthesized beliefs — derived from
    # experience, reflection, and the closed learning loop. They are not retrieved
    # notes; they are what the mind has come to UNDERSTAND. They speak first.
    _BELIEF_CLAIMS = {"ESTABLISHED_FACT", "BELIEF", "STRONG_THEORY", "CONVICTION", "DIRECTIVE"}
    wisdom_entries = [
        r for r in resonant
        if r.category == "WISDOM_EXTRACTED" and r.claim_type in _BELIEF_CLAIMS
    ]
    if wisdom_entries and intent == "questioning":
        wisdom_sentences = _extract_mind_voice(
            wisdom_entries, max_per_entry=2, total_max=2, query_tokens=query_tokens
        )
        parts.extend(wisdom_sentences)

    # --- STATE LAYER ---
    # One sentence from state-resonant content when state is active (addresses HOW sender is)
    if state.activation > 0.25 and state_resonant:
        state_sentences = _extract_mind_voice(
            state_resonant, max_per_entry=1, total_max=1, query_tokens=query_tokens
        )
        parts.extend(state_sentences)

    # No concept resonance found — the mind has nothing on this yet.
    # Return empty so the gap-detection in seed_mind_conversation can seed it.
    if not resonant:
        return ""

    # --- KNOWLEDGE LAYER ---
    # For questions: lead with relevant titles (synthesized insights), then support
    # with content sentences biased by question type.
    if intent == "questioning" and query_tokens:
        # Bias entry order toward categories most suited to the question type
        _Q_CATEGORY_BIAS: Dict[str, List[str]] = {
            "what":       ["MISSION_PURPOSE", "REALITY_FRAMEWORK", "MORAL_ROOT", "SELF_REFLECTION"],
            "how":        ["TECHNICAL_ARCHITECTURE", "REFINED_FOUNDER_GUIDANCE", "REALITY_FRAMEWORK"],
            "why":        ["MORAL_ROOT", "MISSION_PURPOSE", "SUBCONSCIOUS_PATTERN", "SELF_REFLECTION"],
            "who":        ["MISSION_PURPOSE", "SELF_REFLECTION", "MORAL_ROOT"],
            "definition": ["MISSION_PURPOSE", "REALITY_FRAMEWORK", "MORAL_ROOT"],
            "capability": ["TECHNICAL_ARCHITECTURE", "REFINED_FOUNDER_GUIDANCE", "MISSION_PURPOSE"],
        }
        biased_cats = _Q_CATEGORY_BIAS.get(q_type or "", [])
        if biased_cats:
            priority_entries = [r for r in resonant if r.category in biased_cats]
            other_entries    = [r for r in resonant if r.category not in biased_cats]
            ordered = priority_entries + other_entries
        else:
            ordered = resonant

        # Skip WISDOM_EXTRACTED entries already included in wisdom layer
        wisdom_ids = {e.entry_id for e in wisdom_entries}
        ordered_non_wisdom = [r for r in ordered if r.entry_id not in wisdom_ids]

        # Lead with the most relevant title(s) — direct answer statements
        title_answers = _titles_as_candidates(ordered_non_wisdom[:6], query_tokens, max_n=2)
        parts.extend(title_answers)

        # Follow with supporting sentences from content
        content_sentences = _extract_mind_voice(
            ordered_non_wisdom, max_per_entry=2, total_max=3, query_tokens=query_tokens
        )
        # Deduplicate: skip sentences too close to a title or wisdom already added
        existing_tokens = set(w for t in (title_answers + list(parts)) for w in re.split(r'\W+', t.lower()))
        for s in content_sentences:
            s_tokens = set(re.split(r'\W+', s.lower()))
            overlap = len(existing_tokens & s_tokens) / max(len(s_tokens), 1)
            if overlap < 0.6:  # not redundant
                parts.append(s)

    else:
        # Non-question intents: extract voice ranked by query tokens if available
        content_sentences = _extract_mind_voice(
            resonant, max_per_entry=2, total_max=4, query_tokens=query_tokens
        )
        parts.extend(content_sentences)

    return "\n\n".join(parts).strip()
